# Probabilistic modelling of Weather

Reference:

https://www.youtube.com/watch?v=K-8F_zDMDUI

In [4]:
import numpy as np 
import matplotlib.pyplot as plt

In [5]:
A = np.array([[.5,.5,.25],[.25,0,.25],[.25,.5,.5]])

In [7]:
# the weather state todday in a column vector formate 
xtoday = np.array([[1],[0],[0]])

In [9]:
# Weather probability tomorrow is the multiplication of weather probability today by the probabilities in matrix A
tomorrow = (A@xtoday)
print(tomorrow)

[[0.5 ]
 [0.25]
 [0.25]]


In [12]:
# create a loop to find the weather in the coming 50 days 
for k in range(50):
    # initiate xtoday, the weather today is known 
    xtoday = np.array([[0],[1],[0]])

    xtomorrow = A@xtoday
    print(k)
    print(xtomorrow)
    print('    ')
    xtoday = xtomorrow
    

0
[[0.5]
 [0. ]
 [0.5]]
    
1
[[0.5]
 [0. ]
 [0.5]]
    
2
[[0.5]
 [0. ]
 [0.5]]
    
3
[[0.5]
 [0. ]
 [0.5]]
    
4
[[0.5]
 [0. ]
 [0.5]]
    
5
[[0.5]
 [0. ]
 [0.5]]
    
6
[[0.5]
 [0. ]
 [0.5]]
    
7
[[0.5]
 [0. ]
 [0.5]]
    
8
[[0.5]
 [0. ]
 [0.5]]
    
9
[[0.5]
 [0. ]
 [0.5]]
    
10
[[0.5]
 [0. ]
 [0.5]]
    
11
[[0.5]
 [0. ]
 [0.5]]
    
12
[[0.5]
 [0. ]
 [0.5]]
    
13
[[0.5]
 [0. ]
 [0.5]]
    
14
[[0.5]
 [0. ]
 [0.5]]
    
15
[[0.5]
 [0. ]
 [0.5]]
    
16
[[0.5]
 [0. ]
 [0.5]]
    
17
[[0.5]
 [0. ]
 [0.5]]
    
18
[[0.5]
 [0. ]
 [0.5]]
    
19
[[0.5]
 [0. ]
 [0.5]]
    
20
[[0.5]
 [0. ]
 [0.5]]
    
21
[[0.5]
 [0. ]
 [0.5]]
    
22
[[0.5]
 [0. ]
 [0.5]]
    
23
[[0.5]
 [0. ]
 [0.5]]
    
24
[[0.5]
 [0. ]
 [0.5]]
    
25
[[0.5]
 [0. ]
 [0.5]]
    
26
[[0.5]
 [0. ]
 [0.5]]
    
27
[[0.5]
 [0. ]
 [0.5]]
    
28
[[0.5]
 [0. ]
 [0.5]]
    
29
[[0.5]
 [0. ]
 [0.5]]
    
30
[[0.5]
 [0. ]
 [0.5]]
    
31
[[0.5]
 [0. ]
 [0.5]]
    
32
[[0.5]
 [0. ]
 [0.5]]
    
33
[[0.5]
 [0. ]
 [0